version: "3"
services:
  app:
    image: node:22.12
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    entrypoint:
      - sh
    command:
      - -c
      - |
        npm install
        npm run build
        npm run start
    tty: true
